name: CMake Build Matrix

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.os }}-${{ matrix.config.cc }}-${{ matrix.config.build }}
    runs-on: ${{ matrix.config.os }}
    env:
      CPM_SOURCE_CACHE: "${{ github.workspace }}/.cache/cpm"
      CCACHE_BASE_DIR: "${{ github.workspace }}/.cache"
      CCACHE_DIR: "${{ github.workspace }}/.cache/ccache"
      CCACHE_COMPRESS: "true"
      CCACHE_COMPRESS_LEVEL: "6"
      CCACHE_MAXSIZE: "600M"
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              os: windows-latest,
              build: Release,
              cc: "cl", cxx: "cl",
              ccache: sccache,
            }
          - {
              os: ubuntu-latest,
              build: Release,
              cc: "gcc", cxx: "g++",
              ccache: ccache,
            }
          - {
              os: ubuntu-latest,
              build: Debug,
              cc: "gcc", cxx: "g++",
              ccache: ccache,
            }
          - {
              os: macos-latest,
              build: Release,
              cc: "clang", cxx: "clang++",
              ccache: ccache,
            }
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: Kaven-Universe/github-action-current-date-time@v1
        id: timestamp
        with:
          format: "yyyy-MM-dd-HH-mm-ss-SSS"

      - uses: actions/cache@v4
        name: Restore CPM source cache
        with:
          path: .cache/cpm
          key: cpm-${{ steps.timestamp.outputs.time }}
          restore-keys: |
            cpm-

      - uses: hendrikmuhs/ccache-action@v1.2
        name: Restore ccache cache
        with:
          variant: ${{ matrix.config.ccache }}
          key: ${{ github.jobs[github.job].name }}-${{ github.ref_name }}-ccache-${{ steps.timestamp.outputs.time }}
          restore-keys: |
            ${{ github.jobs[github.job].name }}-${{ github.ref_name }}-ccache-
            ${{ github.jobs[github.job].name }}-main-ccache-

      - uses: microsoft/setup-msbuild@v2
        if: ${{ matrix.config.os == 'windows-latest' }}

      - uses: lukka/get-cmake@latest

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.config.build }} -DREALM_BUILD_TESTS=ON -DREALM_BUILD_BENCHMARKS=ON -DREALM_BUILD_TUTORIALS=ON -DREALM_BUILD_EXAMPLES=ON -DREALM_ENABLE_GASNETEX=OFF

      - name: Build
        run: |
          cmake --build build --parallel 4 --config ${{ matrix.config.build }}

      - name: Run tests
        run: |
          ctest --test-dir build --output-on-failure --parallel 4 --build-config ${{ matrix.config.build }}

      - name: Test Install
        run: |
          cmake --install build --parallel 4 --prefix install --config ${{ matrix.config.build }}
