name: ci

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages

jobs:
  build:
    name: ${{ matrix.config.os }}-${{ matrix.config.cc }}-${{ matrix.config.build }}
    runs-on: ${{ matrix.config.os }}
    env:
      CPM_SOURCE_CACHE: "${{ github.workspace }}/.cache/cpm"
      CCACHE_BASEDIR: ${{ github.workspace }}
      CCACHE_COMPRESS: "true"
      CCACHE_COMPRESS_LEVEL: "6"
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              os: windows-latest,
              build: Release,
              cc: "cl", cxx: "cl",
              ccache: sccache,
            }
          - {
              os: ubuntu-latest,
              build: Release,
              cc: "gcc", cxx: "g++",
              ccache: ccache,
            }
          - {
              os: ubuntu-latest,
              build: Debug,
              cc: "gcc", cxx: "g++",
              ccache: ccache,
            }
          - {
              os: macos-latest,
              build: Release,
              cc: "clang", cxx: "clang++",
              ccache: ccache,
            }
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: Kaven-Universe/github-action-current-date-time@v1
        id: timestamp
        with:
          format: "yyyy-MM-dd-HH-mm-ss-SSS"

      - uses: actions/cache@v4
        name: Restore CPM source cache
        with:
          path: .cache/cpm
          key: cpm-${{ steps.timestamp.outputs.time }}
          restore-keys: |
            cpm-

      - uses: hendrikmuhs/ccache-action@v1.2
        name: Restore ccache cache
        with:
          variant: ${{ matrix.config.ccache }}
          append-timestamp: true

          key: ${{ github.jobs[github.job].name }}-${{ github.ref_name }}-ccache
          restore-keys: |
            ${{ github.jobs[github.job].name }}-${{ github.ref_name }}-ccache
            ${{ github.jobs[github.job].name }}-main-ccache

      - uses: microsoft/setup-msbuild@v2
        if: ${{ matrix.config.os == 'windows-latest' }}

      - uses: lukka/get-cmake@latest

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_C_COMPILER_LAUNCHER=${{ matrix.config.ccache }} -DCMAKE_CXX_COMPILER_LAUNCHER=${{ matrix.config.ccache }} -DCMAKE_BUILD_TYPE=${{ matrix.config.build }} -DREALM_BUILD_TESTS=ON -DREALM_BUILD_BENCHMARKS=ON -DREALM_BUILD_TUTORIALS=ON -DREALM_BUILD_EXAMPLES=ON -DREALM_ENABLE_GASNETEX=OFF

      - name: Build
        run: |
          cmake --build build --parallel 4 --config ${{ matrix.config.build }}

      - name: Run tests
        run: |
          ctest --output-junit ${{ github.workspace }}/${{ github.sha }}-results.xml --timeout 240 --test-dir build --output-on-failure --parallel 4 --build-config ${{ matrix.config.build }}
      
      - uses: test-summary/action@v2
        if: always()
        with:
          paths: "${{ github.workspace }}/${{ github.sha }}-results.xml"

      - name: Test Install
        run: |
          cmake --install build --parallel 4 --prefix install --config ${{ matrix.config.build }}

  docs:
    name: Build Docs
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    strategy:
      fail-fast: false
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen doxygen-latex graphviz cmake

      - uses: actions/checkout@v4.2.2
        with:
          path: realm-src

      - name: Get safe ref
        id: safe
        run: |
          echo ref=${GITHUB_REF_NAME//\//-} >> ${GITHUB_OUTPUT}

      - name: Build
        run: |
          cmake -S realm-src -B build -DCMAKE_BUILD_TYPE=Release -DREALM_ENABLE_UCX=OFF -DREALM_ENABLE_GASNETEX=OFF -DREALM_BUILD_DOCS=ON -DREALM_GENERATE_HTML=ON
          make -C build docs
          cmake --install build --component Realm_doc --prefix install

      - uses: actions/upload-artifact@v4
        with:
          name: docs-${{ steps.safe.outputs.ref }}
          path: build/docs/html
          if-no-files-found: error
          retention-days: 2
          overwrite: true

      - uses: actions/checkout@v4.2.2
        if: ${{ github.event_name == 'push' && (github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/v')) }}
        with:
          ref: gh-pages
          path: gh-pages

      - name: Publish Docs
        if: ${{ github.event_name == 'push' && (github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/v')) }}
        run: |
          rm -rf gh-pages/doc/${{ steps.safe.outputs.ref }}*
          mv install/share/doc/Realm/realm-* gh-pages/doc/${{ steps.safe.outputs.ref }}
          cd gh-pages/doc
          find * -maxdepth 0 -type d > doc-versions
          git config --global user.name "GitHub Docs Builder"
          git config --global user.email "docs-builder@users.noreply.github.com"
          git add ${{ steps.safe.outputs.ref }} doc-versions
          git status
          git commit -m "Update docs for ${{ github.ref_name }}"
          git fetch origin
          git rebase --strategy-option=theirs origin/gh-pages --verbose
          git push --verbose